repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-aws-credentials
  - id: detect-private-key
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.0
  hooks:
  - id: no-browser-statement
  - id: no-debug-statement
  - id: lintr
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]