name: Pulumi
on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'pulumi/**'
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::767397675902:role/hubverse-pulumi-role
          aws-region: us-east-1
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: hubverse/hubverse
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.BSWEGER_PULUMI_DEM }}
