name: Pulumi
on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'pulumi/**'
jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: hubverse/hubverse
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.BSWEGER_PULUMI_DEMO }}