name: Pulumi Preview
on:
  workflow_dispatch:
  pull_request:
    branches: main

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  preview:
    name: Preview infrastructure changes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pulumi
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Installing dependencies 📦️
        run: pip install -r requirements.txt
      
      - name: Configure AWS credentials 🔐
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767397675902:role/hubverse-administration
          aws-region: us-east-1

      - name: Previewing infrastructure 👀
        uses: pulumi/actions@v5
        with:
          command: preview
          work-dir: ./pulumi
          stack-name: bsweger/hubverse-aws/hubverse
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.BSWEGER_PULUMI_DEMO }}