name: Run Code Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            cache: true
      - name: Install dependencies
        run: pip install -r pulumi/requirements.txt
      - name: lint
        run: ruff check
      - name: type check
        run: mypy . --ignore-missing-imports

      - name: Install dependencies 📦️
        run: |
          pip install -r requirements/requirements.txt -e .
          pip install -r requirements/dev-requirements.txt

      - name: lint 🪩
        run: ruff check

      - name: type check 📝
        run: mypy . --ignore-missing-imports
